"use client";

import { useEffect, useState } from "react";

const EVENTS = [
  "Volatility regime recalibrated",
  "Market structure context updated",
  "Risk exposure parameters reviewed",
  "Liquidity conditions reassessed",
  "Execution bias synchronized",
  "Macro sentiment layer refreshed",
  "Order flow imbalance normalized",
  "Adaptive confidence thresholds adjusted",
];

const MAX_LOGS = 6;

export default function AITimeline() {
  const [logs, setLogs] = useState<string[]>([]);

  useEffect(() => {
    const id = setInterval(() => {
      setLogs((prev) => {
        const next = EVENTS[Math.floor(Math.random() * EVENTS.length)];
        const time = new Date().toLocaleTimeString([], {
          hour: "2-digit",
          minute: "2-digit",
        });

        return [`[${time}] ${next}`, ...prev].slice(0, MAX_LOGS);
      });
    }, 2100);

    return () => clearInterval(id);
  }, []);

  return (
    <div
      className="
        bg-[#0B1220]
        border border-[#1F2937]
        rounded-2xl
        p-4
        shadow-[inset_0_1px_0_#ffffff08]
        animate-fade-in
      "
    >
      <div className="flex items-center justify-between mb-1">
        <h3 className="text-sm font-semibold text-[#22ff88]">
          AI Market Analysis Timeline
        </h3>
        <span className="text-[10px] text-gray-500">LIVE</span>
      </div>

      <p className="text-[11px] text-gray-500 mb-3">
        Continuous analytical context updates generated by the system
      </p>

      <ul className="space-y-2 text-[12px] text-gray-400">
        {logs.map((log, i) => (
          <li
            key={i}
            className="animate-fadeInUp leading-relaxed"
          >
            {log}
          </li>
        ))}
      </ul>

      <div className="mt-3 pt-2 border-t border-[#1F2937]">
        <p className="text-[10px] text-gray-500">
          Informational system events only — no trades are executed or triggered
        </p>
      </div>
    </div>
  );
}
