"use client";

import { useEffect, useState } from "react";

const EVENTS = [
  "Volatility regime recalibrated",
  "Market structure context updated",
  "Risk exposure parameters reviewed",
  "Liquidity conditions reassessed",
  "Execution bias synchronized",
];

export default function AITimeline() {
  const [logs, setLogs] = useState<string[]>([]);

  useEffect(() => {
    const id = setInterval(() => {
      setLogs((prev) => {
        const next = EVENTS[Math.floor(Math.random() * EVENTS.length)];
        const time = new Date().toLocaleTimeString([], {
          hour: "2-digit",
          minute: "2-digit",
        });

        return [`[${time}] ${next}`, ...prev].slice(0, 5);
      });
    }, 2200);

    return () => clearInterval(id);
  }, []);

  return (
    <div className="bg-[#0B0F18] border border-[#1F2937] rounded-xl p-4">
      <h3 className="text-sm font-semibold text-[#22ff88] mb-1">
        AI Market Analysis Timeline
      </h3>

      <p className="text-[11px] text-gray-500 mb-3">
        Real-time analytical context updates generated by the AI system
      </p>

      <ul className="space-y-2 text-[12px] text-gray-400">
        {logs.map((l, i) => (
          <li key={i} className="animate-fadeInUp">
            {l}
          </li>
        ))}
      </ul>

      <p className="mt-3 text-[10px] text-gray-500">
        Informational system events only — no trades are executed or triggered
      </p>
    </div>
  );
}

